// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://ouafrfkeudajmzyfdhgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91YWZyZmtldWRham16eWZkaGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTI0MDYsImV4cCI6MjA3MzA2ODQwNn0.8WPo4HjSL2gaf0VjVpL76-67Z2ijhWUGXkjzf620O-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});